networks:
    dcp:
        name: dcp
        external: true

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          - APP_NAME=APIService
    image: api-service:latest
    container_name: api-service
    ports:
        - "8080:8080"
    environment:
        - PORT=${PORT}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
        - .env
    networks:
        - dcp
