server:
    port: ${PORT:8080}
    servlet:
        context-path: /

spring:
    application:
        name: api-service

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:9998}/${DB_NAME:postgres}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none # Prevents Hibernate from dropping, creating, or modifying tables
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    use_streams_for_binary: false
                    wrap_result_sets: false
                cache:
                    use_query_cache: false

logging:
    level:
        root: INFO
        org.springframework.web: INFO


properties:
    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:-*}
