server:
    port: ${PORT:8080}
    servlet:
        context-path: /

spring:
    application:
        name: api-service

    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:9998}/${DB_NAME:postgres}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        jpa:
            hibernate:
                ddl-auto: update
            show-sql: true

logging:
    level:
        root: INFO
        org.springframework.web: INFO

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
