name: Java CI with Maven

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:

        runs-on: ubuntu-latest

        env:
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: testdb
            DB_USERNAME: testuser
            DB_PASSWORD: testpassword
            PORT: 8080
            CORS_ALLOWED_ORIGINS: http://localhost:8080

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'

            - name: Install PostgreSQL client
              run: sudo apt-get install -y postgresql-client

            - name: Start PostgreSQL service
              run: |
                  sudo apt-get update
                  sudo apt-get install -y postgresql postgresql-contrib
                  sudo service postgresql start
                  sudo -u postgres psql -c "CREATE DATABASE testdb;"
                  sudo -u postgres psql -c "CREATE USER testuser WITH ENCRYPTED PASSWORD 'testpassword';"
                  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;"

            - name: Build with Maven
              run: mvn clean install -DskipTests -Dspring.profiles.active=test

            - name: Run tests
              run: mvn test -Dspring.profiles.active=test
